name: CI/CD Pipeline for Azure Function

on:
  push:
    branches:
      - main # Trigger the pushes to the 'main' branch.


env:
  AZURE_RESOURCE_GROUP_NAME: 'crc-rg'
  AZURE_FUNCTION_APP_NAME: 'get_visitor_counter'
  AZURE_REGION: 'canadacentral'


jobs:
  build-and-test: # Can be renamed to anything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Tests
        run: |
          pytest backend/


  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: Prod
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: Deploy Azure Bicep Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          template: './deployment/main.bicep'
          parameters: 'functionAppName=${{ env.AZURE_FUNCTION_APP_NAME }} location=${{ env.AZURE_REGION }}'

      - name: 'Zip and Deploy Function App Code'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: './backend'
          scm-do-build-during-deployment: true

       - name: Logout from Azure
         run: |
           az logout
